services:

  db:
    image: mysql:8.0
    container_name: ecomm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecom_mono
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecomm_net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ecom_mono
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    networks:
      - ecomm_net

  product-service:
    build: ./product-service
    container_name: product-service
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ecom_mono
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    networks:
      - ecomm_net

  order-service:
    build: ./order-service
    container_name: order-service
    restart: always
    depends_on:
      - db
      - product-service
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ecom_mono
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      PRODUCT_SERVICE_URL: http://product-service:5003
    networks:
      - ecomm_net

  # ---------- Frontend (server-rendered UI, browser-facing) ----------
  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    restart: always
    depends_on:
      - auth-service
      - product-service
      - order-service
    ports:
      - "5001:5001"
    environment:
      FLASK_SECRET_KEY: change-this-to-a-long-random-value
      AUTH_SERVICE_URL: http://auth-service:5002
      PRODUCT_SERVICE_URL: http://product-service:5003
      ORDER_SERVICE_URL: http://order-service:5004
    networks:
      - ecomm_net

volumes:
  db_data:

networks:
  ecomm_net:
    driver: bridge